// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: rate.proto

package rate_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindRateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwgrId  int64  `protobuf:"varint,1,opt,name=gwgrId,proto3" json:"gwgrId,omitempty"`
	DateAt  int64  `protobuf:"varint,2,opt,name=dateAt,proto3" json:"dateAt,omitempty"`
	Dir     uint32 `protobuf:"varint,3,opt,name=dir,proto3" json:"dir,omitempty"`
	ANumber uint64 `protobuf:"varint,4,opt,name=aNumber,proto3" json:"aNumber,omitempty"`
	BNumber uint64 `protobuf:"varint,5,opt,name=bNumber,proto3" json:"bNumber,omitempty"`
}

func (x *FindRateRequest) Reset() {
	*x = FindRateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRateRequest) ProtoMessage() {}

func (x *FindRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRateRequest.ProtoReflect.Descriptor instead.
func (*FindRateRequest) Descriptor() ([]byte, []int) {
	return file_rate_proto_rawDescGZIP(), []int{0}
}

func (x *FindRateRequest) GetGwgrId() int64 {
	if x != nil {
		return x.GwgrId
	}
	return 0
}

func (x *FindRateRequest) GetDateAt() int64 {
	if x != nil {
		return x.DateAt
	}
	return 0
}

func (x *FindRateRequest) GetDir() uint32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *FindRateRequest) GetANumber() uint64 {
	if x != nil {
		return x.ANumber
	}
	return 0
}

func (x *FindRateRequest) GetBNumber() uint64 {
	if x != nil {
		return x.BNumber
	}
	return 0
}

type RateBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RmsrId    int64   `protobuf:"varint,1,opt,name=rmsrId,proto3" json:"rmsrId,omitempty"`
	PriceBase float64 `protobuf:"fixed64,2,opt,name=priceBase,proto3" json:"priceBase,omitempty"`
}

func (x *RateBase) Reset() {
	*x = RateBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateBase) ProtoMessage() {}

func (x *RateBase) ProtoReflect() protoreflect.Message {
	mi := &file_rate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateBase.ProtoReflect.Descriptor instead.
func (*RateBase) Descriptor() ([]byte, []int) {
	return file_rate_proto_rawDescGZIP(), []int{1}
}

func (x *RateBase) GetRmsrId() int64 {
	if x != nil {
		return x.RmsrId
	}
	return 0
}

func (x *RateBase) GetPriceBase() float64 {
	if x != nil {
		return x.PriceBase
	}
	return 0
}

type FindRateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate *RateBase `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *FindRateResponse) Reset() {
	*x = FindRateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRateResponse) ProtoMessage() {}

func (x *FindRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRateResponse.ProtoReflect.Descriptor instead.
func (*FindRateResponse) Descriptor() ([]byte, []int) {
	return file_rate_proto_rawDescGZIP(), []int{2}
}

func (x *FindRateResponse) GetRate() *RateBase {
	if x != nil {
		return x.Rate
	}
	return nil
}

type FindSupRatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateAt  int64  `protobuf:"varint,1,opt,name=dateAt,proto3" json:"dateAt,omitempty"`
	ANumber uint64 `protobuf:"varint,2,opt,name=aNumber,proto3" json:"aNumber,omitempty"`
	BNumber uint64 `protobuf:"varint,3,opt,name=bNumber,proto3" json:"bNumber,omitempty"`
}

func (x *FindSupRatesRequest) Reset() {
	*x = FindSupRatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSupRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSupRatesRequest) ProtoMessage() {}

func (x *FindSupRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSupRatesRequest.ProtoReflect.Descriptor instead.
func (*FindSupRatesRequest) Descriptor() ([]byte, []int) {
	return file_rate_proto_rawDescGZIP(), []int{3}
}

func (x *FindSupRatesRequest) GetDateAt() int64 {
	if x != nil {
		return x.DateAt
	}
	return 0
}

func (x *FindSupRatesRequest) GetANumber() uint64 {
	if x != nil {
		return x.ANumber
	}
	return 0
}

func (x *FindSupRatesRequest) GetBNumber() uint64 {
	if x != nil {
		return x.BNumber
	}
	return 0
}

type SupRateBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwgrId int64     `protobuf:"varint,1,opt,name=gwgrId,proto3" json:"gwgrId,omitempty"`
	Rate   *RateBase `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *SupRateBase) Reset() {
	*x = SupRateBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupRateBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupRateBase) ProtoMessage() {}

func (x *SupRateBase) ProtoReflect() protoreflect.Message {
	mi := &file_rate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupRateBase.ProtoReflect.Descriptor instead.
func (*SupRateBase) Descriptor() ([]byte, []int) {
	return file_rate_proto_rawDescGZIP(), []int{4}
}

func (x *SupRateBase) GetGwgrId() int64 {
	if x != nil {
		return x.GwgrId
	}
	return 0
}

func (x *SupRateBase) GetRate() *RateBase {
	if x != nil {
		return x.Rate
	}
	return nil
}

type FindSupRatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupRatesBase []*SupRateBase `protobuf:"bytes,1,rep,name=supRatesBase,proto3" json:"supRatesBase,omitempty"`
}

func (x *FindSupRatesResponse) Reset() {
	*x = FindSupRatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSupRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSupRatesResponse) ProtoMessage() {}

func (x *FindSupRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSupRatesResponse.ProtoReflect.Descriptor instead.
func (*FindSupRatesResponse) Descriptor() ([]byte, []int) {
	return file_rate_proto_rawDescGZIP(), []int{5}
}

func (x *FindSupRatesResponse) GetSupRatesBase() []*SupRateBase {
	if x != nil {
		return x.SupRatesBase
	}
	return nil
}

var File_rate_proto protoreflect.FileDescriptor

var file_rate_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x61,
	0x74, 0x65, 0x5f, 0x76, 0x31, 0x22, 0x87, 0x01, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x77, 0x67,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x77, 0x67, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x40, 0x0a, 0x08, 0x52, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6d, 0x73, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6d, 0x73,
	0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x42, 0x61, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x22, 0x39, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x61,
	0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x61, 0x0a, 0x13,
	0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x70, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x4c, 0x0a, 0x0b, 0x53, 0x75, 0x70, 0x52, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x67, 0x77, 0x67, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x67, 0x77, 0x67, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x52,
	0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x50, 0x0a,
	0x14, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x70, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x73, 0x75, 0x70, 0x52, 0x61, 0x74, 0x65,
	0x73, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x61,
	0x74, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x52, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x0c, 0x73, 0x75, 0x70, 0x52, 0x61, 0x74, 0x65, 0x73, 0x42, 0x61, 0x73, 0x65, 0x32,
	0x96, 0x01, 0x0a, 0x06, 0x52, 0x61, 0x74, 0x65, 0x56, 0x31, 0x12, 0x3f, 0x0a, 0x08, 0x46, 0x69,
	0x6e, 0x64, 0x52, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x76, 0x31,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x46,
	0x69, 0x6e, 0x64, 0x53, 0x75, 0x70, 0x52, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x72, 0x61,
	0x74, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x70, 0x52, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x61, 0x74, 0x65,
	0x5f, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x70, 0x52, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x61, 0x64, 0x69, 0x6d, 0x47, 0x6f, 0x73, 0x73,
	0x69, 0x70, 0x2f, 0x64, 0x72, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x76, 0x31, 0x3b, 0x72,
	0x61, 0x74, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rate_proto_rawDescOnce sync.Once
	file_rate_proto_rawDescData = file_rate_proto_rawDesc
)

func file_rate_proto_rawDescGZIP() []byte {
	file_rate_proto_rawDescOnce.Do(func() {
		file_rate_proto_rawDescData = protoimpl.X.CompressGZIP(file_rate_proto_rawDescData)
	})
	return file_rate_proto_rawDescData
}

var file_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rate_proto_goTypes = []interface{}{
	(*FindRateRequest)(nil),      // 0: rate_v1.FindRateRequest
	(*RateBase)(nil),             // 1: rate_v1.RateBase
	(*FindRateResponse)(nil),     // 2: rate_v1.FindRateResponse
	(*FindSupRatesRequest)(nil),  // 3: rate_v1.FindSupRatesRequest
	(*SupRateBase)(nil),          // 4: rate_v1.SupRateBase
	(*FindSupRatesResponse)(nil), // 5: rate_v1.FindSupRatesResponse
}
var file_rate_proto_depIdxs = []int32{
	1, // 0: rate_v1.FindRateResponse.rate:type_name -> rate_v1.RateBase
	1, // 1: rate_v1.SupRateBase.rate:type_name -> rate_v1.RateBase
	4, // 2: rate_v1.FindSupRatesResponse.supRatesBase:type_name -> rate_v1.SupRateBase
	0, // 3: rate_v1.RateV1.FindRate:input_type -> rate_v1.FindRateRequest
	3, // 4: rate_v1.RateV1.FindSupRates:input_type -> rate_v1.FindSupRatesRequest
	2, // 5: rate_v1.RateV1.FindRate:output_type -> rate_v1.FindRateResponse
	5, // 6: rate_v1.RateV1.FindSupRates:output_type -> rate_v1.FindSupRatesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rate_proto_init() }
func file_rate_proto_init() {
	if File_rate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSupRatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupRateBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSupRatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rate_proto_goTypes,
		DependencyIndexes: file_rate_proto_depIdxs,
		MessageInfos:      file_rate_proto_msgTypes,
	}.Build()
	File_rate_proto = out.File
	file_rate_proto_rawDesc = nil
	file_rate_proto_goTypes = nil
	file_rate_proto_depIdxs = nil
}
